[2023-12-21T15:14:50.368-0300] {processor.py:161} INFO - Started process (PID=17669) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T15:14:50.369-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T15:14:50.370-0300] {logging_mixin.py:188} INFO - [2023-12-21T15:14:50.370-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T15:14:50.386-0300] {logging_mixin.py:188} INFO - [2023-12-21T15:14:50.385-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1403
    def eliminar_tablas_temporales():
IndentationError: unexpected indent
[2023-12-21T15:14:50.386-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T15:14:50.502-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.139 seconds
