[2023-12-21T12:58:46.863-0300] {processor.py:161} INFO - Started process (PID=7091) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T12:58:46.865-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T12:58:46.867-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:46.866-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T12:58:46.875-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:46.873-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T12:58:46.875-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:46.875-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T12:58:46.876-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T12:58:46.898-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-12-21T12:59:59.996-0300] {processor.py:161} INFO - Started process (PID=7171) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T12:59:59.998-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:00:00.001-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:00.000-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:00:00.008-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:00.007-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:00:00.009-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:00.009-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:00:00.010-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:00:00.032-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-12-21T13:01:11.209-0300] {processor.py:161} INFO - Started process (PID=7267) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:01:11.211-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:01:11.213-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:11.212-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:01:11.221-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:11.219-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:01:11.221-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:11.221-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:01:11.222-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:01:11.241-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-12-21T13:02:18.116-0300] {processor.py:161} INFO - Started process (PID=7346) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:02:18.131-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:02:18.133-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:18.132-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:02:18.141-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:18.140-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:02:18.141-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:18.141-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:02:18.142-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:02:18.157-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-12-21T13:03:19.695-0300] {processor.py:161} INFO - Started process (PID=7413) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:03:19.697-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:03:19.699-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:19.698-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:03:19.707-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:19.705-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:03:19.707-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:19.707-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:03:19.708-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:03:19.730-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-12-21T13:04:19.389-0300] {processor.py:161} INFO - Started process (PID=7471) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:04:19.391-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:04:19.393-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:19.392-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:04:19.401-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:19.400-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:04:19.402-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:19.401-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:04:19.402-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:04:19.424-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-12-21T13:05:19.194-0300] {processor.py:161} INFO - Started process (PID=7527) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:05:19.196-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:05:19.198-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:05:19.197-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:05:19.206-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:05:19.205-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:05:19.206-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:05:19.206-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:05:19.207-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:05:19.230-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-12-21T13:06:42.012-0300] {processor.py:161} INFO - Started process (PID=7682) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:06:42.015-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:06:42.018-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:42.017-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:06:42.025-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:42.024-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:06:42.026-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:42.026-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:06:42.027-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:06:42.046-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-12-21T13:07:56.610-0300] {processor.py:161} INFO - Started process (PID=7778) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:07:56.621-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:07:56.623-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:07:56.622-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:07:56.631-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:07:56.630-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:07:56.632-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:07:56.632-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:07:56.633-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:07:56.657-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2023-12-21T13:09:00.085-0300] {processor.py:161} INFO - Started process (PID=9195) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:09:00.094-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:09:00.096-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:00.095-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:09:00.101-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:00.100-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:09:00.101-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:00.101-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:09:00.102-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:09:00.118-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-12-21T13:10:07.869-0300] {processor.py:161} INFO - Started process (PID=9386) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:10:07.891-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:10:07.893-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:07.892-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:10:07.898-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:07.897-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:10:07.898-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:07.898-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:10:07.898-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:10:07.914-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-12-21T13:11:16.084-0300] {processor.py:161} INFO - Started process (PID=9769) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:11:16.086-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:11:16.088-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:16.087-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:11:16.096-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:16.095-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:11:16.097-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:16.096-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:11:16.097-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:11:16.115-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-12-21T13:12:17.949-0300] {processor.py:161} INFO - Started process (PID=10071) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:12:17.952-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:12:17.954-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:17.953-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:12:17.961-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:17.960-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:12:17.962-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:17.962-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:12:17.963-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:12:17.985-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-12-21T13:13:21.069-0300] {processor.py:161} INFO - Started process (PID=10277) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:13:21.071-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:13:21.074-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:21.073-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:13:21.081-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:21.080-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:13:21.082-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:21.082-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:13:21.082-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:13:21.104-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-12-21T13:14:23.109-0300] {processor.py:161} INFO - Started process (PID=10337) to work on /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:14:23.111-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-12-21T13:14:23.113-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:14:23.113-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:14:23.121-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:14:23.120-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-12-21T13:14:23.122-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:14:23.121-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-12-21T13:14:23.122-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-12-21T13:14:23.144-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
